# FFmpeg Build Script
# All project paths are derived relative to this script's location.
$ErrorActionPreference = 'Stop'

# ---- Derived project paths (no hardcoded repo path) ----
$scriptDir = $PSScriptRoot
$srcDir    = [IO.Path]::GetFullPath((Join-Path $scriptDir '..'))
$repoRoot  = [IO.Path]::GetFullPath((Join-Path $srcDir '..'))
$buildDir  = Join-Path $repoRoot 'build'
$outDir    = Join-Path $repoRoot 'build_output'
$ffmpegSrc = Join-Path $srcDir 'remotedesk\thridparty\ffmpeg\FFmpeg-n3.4.8'
$ffmpegBuild   = Join-Path $buildDir 'ffmpeg_build'
$ffmpegInstall = Join-Path $outDir 'ffmpeg_install'
$openh264Lib   = Join-Path $outDir 'openh264_install\lib'
$openh264Inc   = Join-Path $outDir 'openh264_install\include\wels'

# ---- Toolchain detection (shared; override via env: QT_BASE_DIR / GIT_BASH / MINGW_MAKE) ----
. (Join-Path $scriptDir 'build_common.ps1')

$toolchain = Get-Toolchain $repoRoot
$gitBash   = Get-GitBash
$mingwBin  = $toolchain.MingwBin

Write-Host "Cleaning build directory..."
if (Test-Path $ffmpegBuild) { Remove-Item -LiteralPath $ffmpegBuild -Recurse -Force }
New-Item -ItemType Directory -Path $ffmpegBuild -Force | Out-Null
New-Item -ItemType Directory -Path "$ffmpegInstall/lib" -Force | Out-Null

Write-Host "Configuring FFmpeg..."
$unixBuild = ConvertTo-UnixPath $ffmpegBuild
$unixSrc   = ConvertTo-UnixPath $ffmpegSrc
$unixInst  = ConvertTo-UnixPath $ffmpegInstall
$msysPath  = ConvertTo-UnixPath $mingwBin
$cflags    = "-I" + $openh264Inc.Replace('\', '/')
$ldflags   = "-L" + $openh264Lib.Replace('\', '/')

# ---- pkg-config support for FFmpeg configure ----
# FFmpeg 3.4.8 detects libopenh264 via pkg-config. Two layers make the
# detection use THIS repo's openh264 no matter where the repo lives:
#   1. QTRD_OPENH264_INC/LIB env vars (repo-relative, derived from $scriptDir)
#      consumed by the global pkg-config shim in Git\usr\bin.
#   2. A repo-local pkg-config shim placed first on PATH (used when the
#      filesystem honors the exec bit; harmless otherwise).
$openh264Fwd = $openh264Install.Replace('\', '/')
$pkgCfgDir = Join-Path $ffmpegBuild 'pkgconfig_tools'
New-Item -ItemType Directory -Path $pkgCfgDir -Force | Out-Null
$shim = @'
#!/bin/sh
# Auto-generated by build_ffmpeg.ps1 - paths derived relative to this repo.
OPENH264_INC="__QTRD_INC__"
OPENH264_LIB="__QTRD_LIB__"
case "$1" in
  --exists)  exit 0 ;;
  --cflags)  echo "-I$OPENH264_INC" ;;
  --libs)    echo "-L$OPENH264_LIB -lopenh264" ;;
  --version) echo "2.6.0" ;;
  *) echo "Package openh264 was not found in the pkg-config search path." >&2; exit 1 ;;
esac
'@
$shim = $shim.Replace('__QTRD_INC__', $openh264Fwd + '/include').Replace('__QTRD_LIB__', $openh264Fwd + '/lib')
$shimFile = Join-Path $pkgCfgDir 'pkg-config'
[System.IO.File]::WriteAllText($shimFile, $shim, (New-Object System.Text.UTF8Encoding($false)))
$unixShimDir = ConvertTo-UnixPath $pkgCfgDir
& $gitBash -lc "chmod +x $unixShimDir/pkg-config 2>/dev/null; true"

& $gitBash -lc "cd $unixBuild && QTRD_OPENH264_INC=${openh264Fwd}/include QTRD_OPENH264_LIB=${openh264Fwd}/lib PATH=${unixShimDir}:${msysPath}:\`$PATH && $unixSrc/configure --cc=gcc --ld=gcc --target-os=mingw32 --arch=x86 --disable-debug --disable-doc --disable-programs --disable-network --disable-avformat --disable-avfilter --disable-avdevice --disable-swresample --disable-postproc --disable-avresample --disable-everything --enable-swscale --enable-libopenh264 --enable-encoder=libopenh264 --enable-decoder=h264 --enable-decoder=mjpeg --enable-decoder=mpeg4 --disable-x86asm --enable-static --disable-shared --extra-cflags=$cflags --extra-ldflags=$ldflags --extra-libs=-lopenh264 --prefix=$unixInst"

Write-Host "Configure result: $LASTEXITCODE"
if (Test-Path "$ffmpegBuild/ffbuild/config.mak") { Write-Host "OK ffbuild/config.mak created" } else { Write-Host "FAILED config.mak not found" }
