// This file is autogenerated. Changes will be overwritten.
#include "ORNZQ2F6DW/moc_authmanager.cpp"
#include "ORNZQ2F6DW/moc_filetransferservice.cpp"
#include "ORNZQ2F6DW/moc_inputmanager.cpp"
#include "ORNZQ2F6DW/moc_rdpserver.cpp"
#include "ORNZQ2F6DW/moc_screencapturer.cpp"
#include "ORNZQ2F6DW/moc_websocketserver.cpp"
