/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-122997-g13e95746ea-20260225"
#endif /* AVUTIL_FFVERSION_H */
